### ISSUE TITLE
Target ES5 instead of ES2020

### ISSUE THREAD

**Issue by aarongarciah** [kripod/react-polymorphic-box#8]
## Motivation

The package is being compiled to ES2020 (see [tsconfig.json](https://github.com/kripod/react-polymorphic-box/blob/361118f0b4ff91538f2170f0d4c2f960811af2a7/tsconfig.json#L5)) and _modern_ JS features as arrow functions are not being transpiled.

## Basic example

As you can see in version 1.1.1 (https://unpkg.com/browse/react-polymorphic-box@1.1.1/dist-web/index.js) arrow functions are not transpiled.

## Details

For people giving support for older browsers (IE11, older versions of Edge, etc.) it woud be great to target ES5 instead of ES2020. The package is so small that it won't affect the size of it.

I can open a PR with this change.

PS: thanks for this package, I love it!

**Comment by kripod** [comment]
Thank you for opening this PR. Unfortunately, the current build pipeline (Pika Pack) only allows using the latest ES version as a target. It is assumed that bundlers will transpile code anyway.

However, I’m leaving this open for future reference, as The build pipeline might change sometime.

**Comment by aarongarciah** [comment]
I understand the reasoning behind the decision but AFAIK most apps don't transpile dependencies. I'm not saying this is right or wrong, just that it's the most common scenario I've seen.

Thank you anyway!

**Comment by aarongarciah** [comment]
Maybe a good choice would to move from Pika Pack to Snowpack, which allows customizing transpilation https://www.snowpack.dev/#browser-support.

**Comment by kripod** [comment]
Thanks for the suggestion! I'm currently working on a module bundling solution of my own. It should be capable of emitting browser-compatible output by default.

**Comment by kripod** [comment]
The latest major version (2.0.1) now has a much smaller footprint by using [`Object.assign`](https://caniuse.com/#feat=mdn-javascript_builtins_object_assign) instead of an inlined function for mimicking property spreading behavior. The runtime is only as small as seen below:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/14854048/87085878-eab26500-c230-11ea-9e91-ac99c8fdeecb.png">

Modern bundlers ship polyfills for `Object.assign`. If not, however, you may use an implementation on your own, [as demonstrated on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill).

**Comment by aarongarciah** [comment]
Thanks @kripod !
